// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ggKZRshDQSX8yrUsGmyABchRdw72C74',
    appId: '1:926312719257:web:10d9c9abd70971bdb0a908',
    messagingSenderId: '926312719257',
    projectId: 'final-project-flatform',
    authDomain: 'final-project-flatform.firebaseapp.com',
    storageBucket: 'final-project-flatform.firebasestorage.app',
    measurementId: 'G-G33ZLWHB5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWgkG6kkD0UeNRZu78O91FhXB0hT-PCNc',
    appId: '1:926312719257:android:3a011246db53bb32b0a908',
    messagingSenderId: '926312719257',
    projectId: 'final-project-flatform',
    storageBucket: 'final-project-flatform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV9Re85SbMQuIhckxISwTI7yYCleyhBac',
    appId: '1:926312719257:ios:737d079d0546aef0b0a908',
    messagingSenderId: '926312719257',
    projectId: 'final-project-flatform',
    storageBucket: 'final-project-flatform.firebasestorage.app',
    iosClientId: '926312719257-qh9t34jivnq06olgc4hs9gg3b46ghmpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectFlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV9Re85SbMQuIhckxISwTI7yYCleyhBac',
    appId: '1:926312719257:ios:737d079d0546aef0b0a908',
    messagingSenderId: '926312719257',
    projectId: 'final-project-flatform',
    storageBucket: 'final-project-flatform.firebasestorage.app',
    iosClientId: '926312719257-qh9t34jivnq06olgc4hs9gg3b46ghmpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectFlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ggKZRshDQSX8yrUsGmyABchRdw72C74',
    appId: '1:926312719257:web:5524274c9426ab2db0a908',
    messagingSenderId: '926312719257',
    projectId: 'final-project-flatform',
    authDomain: 'final-project-flatform.firebaseapp.com',
    storageBucket: 'final-project-flatform.firebasestorage.app',
    measurementId: 'G-0YWJ6MJ1TG',
  );
}
